### ISSUE TITLE
Issue with several python packages

### ISSUE THREAD

**Issue by organicnz** [lablab-ai/whisper-api-flask#5]
Hi everyone,

Thanks so much for the project guys :)

Could you pls help with this error with several python packages? Not sure how to fix it hehe :)

```
sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65

docker -v
Docker version 20.10.23, build 7155243
```

```
docker run -p 5000:5000 whisper-api
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)
```

**Comment by pablosoria** [comment]
Same here

**Comment by justinatienza** [comment]
@organicnz and @pablosoria 
temporarily, you can pin Markupsafe version and this should address the problem

i pinned the version to `MarkupSafe==2.0.1` and it resolved the issue

**Comment by RayMacLewis** [comment]
@justinatienza Can you show us how you did that?

**Comment by cpunt** [comment]
> @justinatienza Can you show us how you did that?

Add ```RUN pip3 install markupsafe==2.0.1``` to the Dockerfile

**Comment by Flafi87** [comment]
Updated readme and dockerfile with information how to fix.
